# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.6
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /home/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8086
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 本地环境
    host: 127.0.0.1
    port: 6379
    database: 1
    password:
    #开发环境 内网redis地址
#    host: 172.20.0.6
#    port: 6380
#    database: 6
#    password: gKnouKDyVE7E4yOyv7EbnFfeRejesQnJyES3iTyDrVSmwhow59
    #生产环境
    #    host: 211.149.159.61
    #    port: 6381
    #    database: 5
    #    password: gKnouKDyVE7E4yOyv7EbnFfeRejesQnJyES3iTyDrVSmwhow59
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥 OjKohFAcvQEnVLsazJtTCSyPGwbHDrmuifXZYpBMkxdNeqlU
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启 swagger
  enabled: true
  # 请求前缀
  pathMapping: /doc
# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
# 模拟用户配置
mock:
  userName: admin
  passWord: z2rwLm#YZ8V^ #默认密码
flowable:
  # 关闭定时任务 job
  async-executor-activate: false
  # 库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
  database-schema-update: true
  idm:
    # 关闭idm引擎 数据库不会创建act_id_*表，流程流转不会使用act_id_*相关的表
    enabled: false
  # 关闭流程定义文件自动检查
  check-process-definitions: false
  # 关闭历史任务定时任务job
  async-history-executor-activate: false


social:
  enabled: true
  domain: localhost
#  oauth:
#    QQ:
#      client-id: xxx
#      client-secret: xxx
#      redirect-uri: http://localhost:/oauthBack
#    WECHAT_OPEN:
#      client-id: xxxxxx
#      client-secret: xxxxxx
#      redirect-uri: http://localhost/oauthBack
#    GITEE:
#      client-id: 6c33b5c4789a5e9c6c1909e86cd667e12b5ddb2666824eb224b49da32604b2cb
#      client-secret: 9aa4f12d51089a65cc128bacee9dcd47069fa637ce312e55f8302ac915df3de6
#      redirect-uri: http://localhost/oauthBack
